[package]
name = "console-subscriber"
version = "0.1.2"
license = "MIT"
edition = "2021"
rust-version = "1.56.0"
authors = ["Eliza Weisman <eliza@buoyant.io>", "Tokio Contributors <team@tokio.rs>",]
readme = "README.md"
repository = "https://github.com/tokio-rs/console/"
homepage = "https://github.com/tokio-rs/console/blob/main/console-subscriber"
description = """
A `tracing-subscriber::Layer` for collecting Tokio console telemetry.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = [
    "tracing",
    "tracing-subscriber",
    "tokio-console",
    "debugging",
    "async",
]

[features]
default = []
parking_lot = ["parking_lot_crate", "tracing-subscriber/parking_lot"]

[dependencies]

tokio = { version = "^1.15", features = ["sync", "time", "macros", "tracing"] }
tokio-stream = "0.1"
thread_local = "1.1.3"
console-api = { version = "0.1.2", path = "../console-api", features = ["transport"] }
tonic = { version = "0.6", features = ["transport"] }
tracing-core = {git = "https://github.com/msdrigg/tracing", branch = "EnvFilterFilter"}
tracing = {git = "https://github.com/msdrigg/tracing", branch = "EnvFilterFilter"}
tracing-subscriber = {git = "https://github.com/msdrigg/tracing", branch = "EnvFilterFilter", default-features = false, features = ["fmt", "registry"] }
futures = { version = "0.3", default-features = false }
hdrhistogram = { version = "7.3.0", default-features = false, features = ["serialization"] }
# The parking_lot dependency is renamed, because we want our `parking_lot`
# feature to also enable `tracing-subscriber`'s parking_lot feature flag.
parking_lot_crate = { package = "parking_lot", version = "0.11", optional = true }
humantime = "2.1.0"

# Required for recording:
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"

[dev-dependencies]
tokio = { version = "^1.7", features = ["full", "rt-multi-thread"] }
futures = "0.3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
